language: node_js

os:
  - osx

matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      node_js: 'v10.0.0'

    - os: osx
      osx_image: xcode10.2
      node_js: 'v10.15.3'

    - os: osx
      osx_image: xcode10.2
      node_js: 'v12.1.0'

    - os: osx
      osx_image: xcode10.1
      node_js: 'v12.1.0'

    - os: osx
      osx_image: xcode9.2
      node_js: 'v12.1.0'

    - os: osx
      osx_image: xcode8
      node_js: 'v12.1.0'

    - os: osx
      osx_image: xcode6.4
      node_js: 'v12.1.0'

cache:
  directories:
    - 'node_modules'

script:
  - npm run clean
  - npm run lint
  - npm run build
  - npm run test
