language: node_js

matrix:
  include:
  - os: osx
    osx_image: xcode11.3 # 10.14
    node_js: v10.0.0

  - os: osx
    osx_image: xcode11.3 # 10.14
    node_js: v13.12.0

  - os: osx
    osx_image: xcode10.1 # 10.13
    node_js: v13.12.0
    env:
    - HDI_MAC_DISABLE_TEST_APFS=1

  - os: osx
    osx_image: xcode9.2 # 10.12
    node_js: v13.12.0
    env:
    - HDI_MAC_DISABLE_TEST_APFS=1

  - os: osx
    osx_image: xcode8 # 10.11
    node_js: v13.12.0
    env:
    - HDI_MAC_DISABLE_TEST_APFS=1

script:
- npm run clean
- npm run lint
- npm run build
- npm run test
